### PR TITLE
clarify purpose of these leaks

### PR DESCRIPTION
**Pull request by shirt-dev**
honestly fuck you man

### CODE REVIEW

**Comment by wvleaks** [comment]
@shirt-dev calm down bro, did this guy fuck your mum or something?

**Comment by shirt-dev** [comment]
Yes

**Comment by RuneMagle** [comment]
😭🤣🤣🤣

**Comment by wvleaks** [comment]
So apparently PHOENiX had a mental breakdown on discord a few months ago and leaked this himself lul. Then Freyja traded it to someone for a CDM and now this more up to date version of vinetrimmer is here for the world to enjoy kek.

https://www.mediafire.com/file/umf0wnwopketgjb/vinetrimmer.zip/file

Happy New Year!

**Pull request closed without merging**
